# LAB | Feature Engineering

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [1]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**Check the shape of your data**

In [3]:
#your code here
spaceship.shape

(8693, 14)

**Check for data types**

In [4]:
#your code here
spaceship.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

**Check for missing values**

In [9]:
#your code heres
spaceship.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [11]:
#your code here
df = spaceship.dropna()
df.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

**Perform Train Test Split**

In [12]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6606 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   6606 non-null   object
 1   HomePlanet    6606 non-null   object
 2   CryoSleep     6606 non-null   object
 3   Cabin         6606 non-null   object
 4   Destination   6606 non-null   object
 5   Age           6606 non-null   float64
 6   VIP           6606 non-null   object
 7   RoomService   6606 non-null   float64
 8   FoodCourt     6606 non-null   float64
 9   ShoppingMall  6606 non-null   float64
 10  Spa           6606 non-null   float64
 11  VRDeck        6606 non-null   float64
 12  Name          6606 non-null   object
 13  Transported   6606 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 729.0+ KB

In [15]:


features = df.drop(columns='Transported')
target = df['Transported']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.20, random_state=10)

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [17]:
#your code here
from sklearn.preprocessing import OneHotEncoder

In [18]:
encoder = OneHotEncoder(sparse_output= False ,handle_unknown= 'ignore')

In [ ]:
encoder.fit(X_train)

In [19]:
X_train = X_train.copy()
X_test = X_test.copy()

In [20]:

X_train["Cabin"] = X_train["Cabin"].str[0]
X_test["Cabin"] = X_test["Cabin"].str[0]
X_train["Cabin"].unique()

array(['F', 'E', 'G', 'A', 'B', 'C', 'D', 'T'], dtype=object)

- Drop PassengerId and Name

In [21]:
#your code here
X_train = X_train.drop(columns=['PassengerId','Name'])

In [22]:
X_test = X_test.drop(columns=['PassengerId','Name'])

In [23]:
cat_cols=["HomePlanet", "CryoSleep", "Cabin", "Destination", "VIP"]

- For non-numerical columns, do dummies.

In [24]:
encoder.fit(X_train[cat_cols])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [34]:
#your code here
encoded_train= encoder.transform(X_train[cat_cols])

In [35]:
encoded_test= encoder.transform(X_test[cat_cols])

In [36]:
encoded_df_train = pd.DataFrame(
    encoded_train,
    columns=encoder.get_feature_names_out(cat_cols),
    index=X_train.index
)

X_train_final = pd.concat([X_train.drop(columns=cat_cols), encoded_df_train], axis=1)

In [37]:
encoded_df_test = pd.DataFrame(
    encoded_test,
    columns=encoder.get_feature_names_out(cat_cols),
    index=X_test.index
)

X_test_final = pd.concat([X_test.drop(columns=cat_cols), encoded_df_test], axis=1)

In [38]:
print(X_train_final.shape, X_test_final.shape)
print(X_test_final.isna().sum().sum())

(5284, 24) (1322, 24)
0

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [40]:
#your code here
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=11)
knn.fit(X_train_final, y_train)
pred = knn.predict(X_test_final)

- Evaluate your model's performance. Comment it

In [42]:
#your code here
from sklearn.metrics import accuracy_score, precision_score, recall_score

print("Accuracy:", accuracy_score(y_test, pred))
print("Precision:", precision_score(y_test, pred))
print("Recall:", recall_score(y_test, pred))

Accuracy: 0.7859304084720121
Precision: 0.7807017543859649
Recall: 0.800599700149925

In [43]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train_final)                          # learn min/max from TRAIN only
X_train_scaled = scaler.transform(X_train_final)
X_test_scaled = scaler.transform(X_test_final)

knn_scaled = KNeighborsClassifier(n_neighbors=11)
knn_scaled.fit(X_train_scaled, y_train)
pred_scaled = knn_scaled.predict(X_test_scaled)

print("Accuracy (scaled):", accuracy_score(y_test, pred_scaled))

Accuracy (scaled): 0.7715582450832073

In [44]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
std_scaler.fit(X_train_final)                     # learn mean/std from TRAIN only
X_train_std = std_scaler.transform(X_train_final)
X_test_std = std_scaler.transform(X_test_final)

knn_std = KNeighborsClassifier(n_neighbors=11)
knn_std.fit(X_train_std, y_train)
pred_std = knn_std.predict(X_test_std)

print("Accuracy (standardized):", accuracy_score(y_test, pred_std))

Accuracy (standardized): 0.7760968229954615